### ISSUE TITLE
Music Track doubles and triples when go to main menu and hit start game button

### ISSUE THREAD

**Issue by GraySfx** [GingaaBread/GitHub-Game-Off-23#40]
In Unity - Music starts on Game start.

Navigate to main menu and hit start game - music track starts again and plays over the original track.  Both simultaneously playing at different times.

Music Object > Trigger Once - is selected.  Not sure how to fix this as of now

**Comment by GingaaBread** [comment]
To stop the event, you can use the `Stop Event` dropdown on the FMOD Studio Event Emitter component.
Might have to play around with this a bit, but it maybe "Object Destroy" or "Object Disable" should do the trick?

Feel free to reference this issue when you commit those changes, then we know :)
